services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\BravoHandlebarsContent\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # TYPO3 handlebars begin
  Cpsit\Typo3HandlebarsComponents\DataProcessing\PageProcessor:
    tags: ['handlebars.processor']
    calls:
      - setPresenter: ['@Cpsit\BravoHandlebarsContent\Presenter\PagePresenter']

  Cpsit\Typo3HandlebarsComponents\Domain\Factory\Page\PageFactory:
    alias: 'Cpsit\BravoHandlebarsContent\Domain\Factory\Page\PageFactory'

  Cpsit\Typo3HandlebarsComponents\Renderer\Component\Page\PageContentRendererInterface:
    alias: 'Cpsit\BravoHandlebarsContent\Renderer\Component\Page\PageContentRenderer'

  # Register all available content objects
  Cpsit\BravoHandlebarsContent\Frontend\ContentObject\HandlebarsTemplateContentObject:
    arguments:
      $renderer: '@handlebars.renderer'
    tags:
      - name: frontend.contentobject
        identifier: 'HANDLEBARSTEMPLATE'
  Cpsit\BravoHandlebarsContent\DataProcessing\HeadlinesDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'headlines'


