services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\BravoHandlebarsContent\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  _instanceof:
    ####
    # handlebars media processors
    ####
    Cpsit\BravoHandlebarsContent\DataProcessing\Media\MediaProcessorInterface:
      tags: [ 'Handlerbars.MediaProcessor' ]

  ####
  # handlebars template content objects
  ####
  Cpsit\BravoHandlebarsContent\Frontend\ContentObject\HandlebarsTemplateContentObject:
    arguments:
      $renderer: '@handlebars.renderer'
      $assetCollector: '@TYPO3\CMS\Core\Page\AssetCollector'
    tags:
      - name: frontend.contentobject
        identifier: 'HANDLEBARSTEMPLATE'

  ####
  # data processors
  ####
  Cpsit\BravoHandlebarsContent\DataProcessing\CollectionDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'collection'

  Cpsit\BravoHandlebarsContent\DataProcessing\EachDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsEach'

  Cpsit\BravoHandlebarsContent\DataProcessing\SerialDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsSerial'

  Cpsit\BravoHandlebarsContent\DataProcessing\TtContentDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'ttContent'

  Cpsit\BravoHandlebarsContent\DataProcessing\TextDataProcessor:
    arguments:
      $dataMap: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\CeTextDataMap'
    tags:
      - name: 'data.processor'
        identifier: 'ceText'

  Cpsit\BravoHandlebarsContent\DataProcessing\TextMediaDataProcessor:
    arguments:
      $dataMap: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\CeTextMediaDataMap'
    tags:
      - name: 'data.processor'
        identifier: 'ceTextMedia'

  Cpsit\BravoHandlebarsContent\DataProcessing\UploadsDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'ceUploads'

  Cpsit\BravoHandlebarsContent\DataProcessing\UnsetDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsUnset'

  Cpsit\BravoHandlebarsContent\DataProcessing\ContentObjectDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsContentObjects'

  Cpsit\BravoHandlebarsContent\DataProcessing\FooterDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'footer'

  Cpsit\BravoHandlebarsContent\DataProcessing\MapFieldsDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsMapFields'

  Cpsit\BravoHandlebarsContent\DataProcessing\DatabaseQueryProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsDatabaseQuery'

  Cpsit\BravoHandlebarsContent\DataProcessing\MediaProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsMedia'

  Cpsit\BravoHandlebarsContent\DataProcessing\FileLikProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsFileLink'

  Cpsit\BravoHandlebarsContent\DataProcessing\LanguageMenuProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsLanguageMenu'

  ####
  # data maps
  ####
  # default implementation for interface
  Cpsit\BravoHandlebarsContent\DataProcessing\Map\DefaultDataMap: ~
  Cpsit\BravoHandlebarsContent\DataProcessing\Map\DataMapInterface: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\DefaultDataMap'

  ####
  # field processors
  ####
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\BodytextProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\FrameClassProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\HeaderLinkProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\LinkProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\PlainTextProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\RelatedRecordsProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\FileCollectionsProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\FileReferencesProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\MediaProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\FlexformProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\Dto\FieldProcessorConfiguration:
    public: true

  Cpsit\BravoHandlebarsContent\Service\MediaDataService:
    public: true
    arguments:
      - !tagged_iterator { tag: Handlerbars.MediaProcessor }
      - '@TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer'

