services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\BravoHandelbarPage\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # TYPO3 handlebars begin
  Cpsit\Typo3HandlebarsComponents\DataProcessing\PageProcessor:
    tags: ['handlebars.processor']
    calls:
      - setPresenter: ['@Cpsit\BravoHandelbarPage\Presenter\PagePresenter']

  Cpsit\Typo3HandlebarsComponents\Domain\Factory\Page\PageFactory:
    alias: 'Cpsit\BravoHandelbarPage\Domain\Factory\Page\PageFactory'

  Cpsit\Typo3HandlebarsComponents\Renderer\Component\Page\PageContentRendererInterface:
    alias: 'Cpsit\BravoHandelbarPage\Renderer\Component\Page\PageContentRenderer'

  # Register all available content objects
  Cpsit\BravoHandelbarPage\Frontend\ContentObject\HandlebarsContentObject:
    arguments:
      $renderer: '@handlebars.renderer'
    tags:
      - name: frontend.contentobject
        identifier: 'HANDLEBARSCONTENT'
  Cpsit\BravoHandelbarPage\DataProcessing\HeadlinesDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'headlines'


