services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\BravoHandlebarsContent\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # TYPO3 handlebars begin
  Cpsit\BravoHandlebarsContent\Frontend\ContentObject\HandlebarsTemplateContentObject:
    arguments:
      $renderer: '@handlebars.renderer'
      $assetCollector: '@TYPO3\CMS\Core\Page\AssetCollector'
    tags:
      - name: frontend.contentobject
        identifier: 'HANDLEBARSTEMPLATE'

  #Cpsit\BravoHandlebarsContent\DataProcessing\HeadlinesDataProcessor:
  #  tags:
  #    - name: 'data.processor'
  #      identifier: 'headlines'

  Cpsit\BravoHandlebarsContent\DataProcessing\TtContentDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'ttContent'

  Cpsit\BravoHandlebarsContent\DataProcessing\TextDataProcessor:
    arguments:
      $dataMap: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\CeTextDataMap'
    tags:
      - name: 'data.processor'
        identifier: 'ceText'

  Cpsit\BravoHandlebarsContent\DataProcessing\TextMediaDataProcessor:
    arguments:
      $dataMap: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\CeTextMediaDataMap'
    tags:
      - name: 'data.processor'
        identifier: 'ceTextMedia'

  Cpsit\BravoHandlebarsContent\DataProcessing\UploadsDataProcessor:
    arguments:
      $dataMap: '@Cpsit\BravoHandlebarsContent\DataProcessing\Map\CeUploadsDataMap'
    tags:
      - name: 'data.processor'
        identifier: 'ceUploads'

  Cpsit\BravoHandlebarsContent\DataProcessing\ContentObjectDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'contentObject'

  Cpsit\BravoHandlebarsContent\DataProcessing\FooterDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'footer'

  Cpsit\BravoHandlebarsContent\DataProcessing\MapFieldsDataProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsMapFields'
  Cpsit\BravoHandlebarsContent\DataProcessing\LinkListProcessor:
    tags:
      - name: 'data.processor'
        identifier: 'handlebarsLinkList'

  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\BodytextProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\HeaderLinkProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\RelatedRecordsProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\FileCollectionsProcessor:
    public: true
  Cpsit\BravoHandlebarsContent\DataProcessing\TtContent\Field\MediaProcessor:
    public: true
